"""PDF report storage: a private GCS bucket plus a signed URL.

The bucket has `public_access_prevention = "enforced"` (see the Terraform), so
there is no way to make a report readable by URL alone. Everyone who opens a
report opens it through a V4 signed URL generated by the job's service account
and dropped into the Google Chat card, which means an engineer needs no Google
Cloud console access to read the morning report -- and someone who leaves the
company loses access when the link expires rather than never.

No Cloud CDN, no Identity-Aware Proxy. Both were considered and both are
infrastructure for a problem this does not have: one PDF a day, read by a
handful of people, all of them within a few hours of it being written.

The GCS archive of raw payloads is gone -- that lives in BigQuery now, where it
can be queried instead of downloaded. This module only handles the PDF.

With no bucket configured it writes to a local directory instead, which is what
makes an offline run produce a real report.
"""

from __future__ import annotations

import logging
from datetime import timedelta
from pathlib import Path

logger = logging.getLogger(__name__)


class ArtifactStore:
    def __init__(self, bucket: str = "", local_dir: str = "artifacts", signed_url_days: int = 7):
        self._bucket_name = bucket
        self._local_dir = Path(local_dir)
        self._signed_url_days = signed_url_days
        self._bucket = None
        if bucket:
            # Imported as a submodule, not `from google.cloud import storage`:
            # `google.cloud` is a namespace package, so what that form resolves
            # to depends on which google-cloud-* distributions happen to be
            # installed. It type-checked before google-cloud-bigquery was added
            # to the venv and stopped afterwards, which is a fragile thing to
            # have in an import line.
            import google.cloud.storage as storage

            self._bucket = storage.Client().bucket(bucket)

    def save(self, path: str, data: bytes, content_type: str = "application/octet-stream") -> str:
        """Store an artifact; returns a signed GCS URL, or a local path offline."""
        if self._bucket is not None:
            blob = self._bucket.blob(path)
            blob.upload_from_string(data, content_type=content_type)
            try:
                return blob.generate_signed_url(
                    version="v4", expiration=timedelta(days=self._signed_url_days), method="GET"
                )
            except Exception:
                # Signing needs a private key or the IAM signBlob permission
                # (roles/iam.serviceAccountTokenCreator on itself, which the
                # Terraform grants). Without it the report is still safely
                # stored -- only the link is missing -- so fall back to the
                # gs:// URI rather than losing the run.
                logger.warning("could not sign a URL for %s; returning the gs:// URI", path)
                return f"gs://{self._bucket_name}/{path}"
        target = self._local_dir / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        return str(target.resolve())

    def save_report(self, run_date: str, data: bytes, extension: str = "pdf") -> str:
        content_type = "application/pdf" if extension == "pdf" else "text/html"
        return self.save(f"reports/triage-report-{run_date}.{extension}", data, content_type)
